---

- name: Prepare to provisioning
  import_playbook: packer_disable_apt-daily.yml

- name: Prepare database host
  hosts: default
  gather_facts: false
  become: true
  vars:
    mongo_bind_ip: '0.0.0.0'
  roles:
    - role: db
