---

- name: Configure app hosts
  hosts: app
  become: true
  gather_facts: false
  vars:
    db_host: '{{ groups["db"] | first }}'
    app_path: /srv/reddit/
  tasks:
    - name: Add unit file for Puma
      notify: restart puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: '644'
    - name: Create a system user
      user:
        name: appuser
        system: true
        home: '{{ app_path }}/'
        create_home: false
    - name: Create conf.d
      file:
        path: /etc/conf.d/
        state: directory
        mode: '755'
    - name: Add config for DB connection
      notify: restart puma
      template:
        src: templates/db_config.j2
        dest: /etc/conf.d/puma.conf
        mode: '644'
    - name: enable puma
      systemd:
        name: puma
        enabled: true
  handlers:
    - name: restart puma
      systemd: name=puma state=restarted
