---

- name: Deploy application
  hosts: app
  become: true
  gather_facts: false
  vars:
    db_host: '{{ groups["db"] | first }}'
    app_path: /srv/reddit/
  tasks:
    - name: Install git
      package:
        name: git
        state: present
    - name: Fetch the latest version of application code
      notify: restart puma
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '{{ app_path }}/'
        version: monolith
        force: true
    - name: Bundle install
      become: false
      bundler:
        state: present
        chdir: '{{ app_path }}/'
  handlers:
    - name: restart puma
      systemd: name=puma state=restarted
