Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vbox|
    vbox.memory = 512
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 512
    libvirt.graphics_type = "spice"
    libvirt.video_type = "virtio"
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "generic/ubuntu1604" # To use with libvirt provider
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.verbose = true,
      ansible.groups = {
        "db" => ["dbserver"],
        "db:vars" => { "mongo_bind_ip" => "0.0.0.0" }
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "generic/ubuntu1604"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
  end
end
